admin_users:
  - name: teaearlgraycold
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+aSBippP139KHLs2dMrfstmhdyZQVIBXFUM02BTelg4usL80AIu7bMiIt2XHIs4NJukF26FjctrT2uIhMIEdytQjBzOfa90vWWZ930OnYm4Bv/pfSKNJKs1QH1sMRfDB2eNbiiMebUihJV3ZKJy3REs6/EyxZAyzO6+VqNnihp/muqbNhlsBqyPSSAyzk4jjA14PWiuaArxR5xtjVVUj9FJF0H4A9DZOtf9neFAFD6qOarEMZivA/FtWcTOZxw2m7v//qMJZsQIcyMksxgh7ys/ZQricDyQ0PEG1/AU4667uit/zvMQxQZWr4LB4EjljMu1BRgxvSw5XZPx0jDlnASBkg3o2LFmqjR4qnVkNOJAYKlOvPP1I3mo+aHiECTXJXMglT/HXLEvKWlS3cEWy25ryemywlTikRfALjbtiJKy+BRt+XzhynEdHFAf7YXnmsVMyeBEbwfvi9MXZkHCkdvoGKHYCHm5aapPGIzPuc5Ac+n+RIleW2z3pplv6S/vdgMoDSBRP6E1k/ZvBdRy/s1iMr8u1vJMgFNCcs62SzA1y4h575+aGG+m47gKqCBc8sUr0X75+PxZzAKo9cdGsTeXu5qeMPngv2nZYVBOa5ZTXENIXzhUru3VUdZ/+HhuynCP3b4ovmDvG7G7GizFCY919Iq085AQG4HmENTIUdAQ== teaearlgraycold"
  - name: creesch
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCr+322+FOWY2FpvtzXMRZfjnTwn2T6+XeJLilFher2U2cdJ73i7bkp5YhJlJlmTQbscJyKutLx4VVb6xRjhYaXnuidl6CrTQxmf5wWaWvWNoKDsM+QGCaFUAA78rXTq4TEFfyui68ht1zaaS2jXGVhnPKXahDn/eFlKgX1E8/39gnigIPa+hWcWhIkfMoKNpPLl/8ipoPDDW9ZbqE8fGnyb5DyYAM7lCjD90QRurWAvGQO97gkJTXHKmIk+Jwrz/FDADZyqVebSLQJ9Y4W7vDaSft2ClAc1moi551JL9kYsymQMstnaKhK2JgfWfibvq1oZqnlbfu4+UYtZAVdXiZnbFZoiLx+COSTrfeUMWOLyxgwMDiexAh6gTqRvP+4F7iFSkDsyc++pDeLRSvPv45ih8UQ23zEI3XWOQpMQJG2iBF3Sfu5IRprV91Lcgda7pgaxwUXnNKOaxVLLwxZVrOU+zAwdq7Xsxy6cVIFWpCGPcMgHuVkOYARz57L9wSWxa0= creesch"

domain: test.nore.gg
certbot_email: me@danangell.com

minecraft_user: minecraft
minecraft_group: "{{ minecraft_user }}"
minecraft_home: "/home/{{ minecraft_user }}"
minecraft_app_dir: "/home/{{ minecraft_user }}/app"
minecraft_log_dir: "/home/{{ minecraft_user }}/script_logs"

web_user: web
web_group: "{{ web_user }}"
web_home: "/home/{{ web_user }}"
web_app_dir: "/home/{{ web_user }}/app"

minecraft_port: 25565
web_port: 3000
bluemap_port: 8100

java_package: openjdk-21-jre-headless
node_major_version: "22"
minecraft_memory: "6G"
minecraft_tmux_session: "minecraft"

repo_root: "{{ playbook_dir }}/../.."
