---
- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    state: present
  loop: "{{ admin_users }}"

- name: Set authorized keys for admin users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
    exclusive: true
  loop: "{{ admin_users }}"

- name: Create minecraft group
  ansible.builtin.group:
    name: "{{ minecraft_group }}"
    state: present

- name: Create minecraft user
  ansible.builtin.user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_home }}"
    shell: /bin/bash
    create_home: true
    state: present

- name: Create minecraft app directory
  ansible.builtin.file:
    path: "{{ minecraft_app_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0755"

- name: Create minecraft script_logs directory
  ansible.builtin.file:
    path: "{{ minecraft_log_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0755"

- name: Create web group
  ansible.builtin.group:
    name: "{{ web_group }}"
    state: present

- name: Create web user
  ansible.builtin.user:
    name: "{{ web_user }}"
    group: "{{ web_group }}"
    home: "{{ web_home }}"
    shell: /bin/bash
    create_home: true
    state: present

- name: Allow group traversal of web home directory
  ansible.builtin.file:
    path: "{{ web_home }}"
    mode: "0710"

- name: Create web app directory
  ansible.builtin.file:
    path: "{{ web_app_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "0755"
