---
- name: Install MySQL server and Python MySQL bindings
  ansible.builtin.apt:
    name:
      - default-mysql-server
      - python3-mysqldb
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy mysqld.cnf
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql


- name: Ensure MySQL is started and enabled
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true

- name: Create bluemap database
  community.mysql.mysql_db:
    name: bluemap
    state: present

- name: Create bluemap database user
  community.mysql.mysql_user:
    name: bluemap
    password: "{{ vault_bluemap_db_password }}"
    priv: "bluemap.*:ALL"
    state: present
